import React from 'react'
import Field from "./Field";


const GameFiled = () => {
    return(
        <div className='board'>
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
            <Field />
        </div>
    )
}
export default GameFiled;